<?php

namespace Database\Seeders;

use App\Models\Area;
use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            [
                'en' => 'Beirut',
                'ar' => 'بيروت',
                'areas' => [
                    ['en' => 'Verdun', 'ar' => 'فردان'],
                    ['en' => 'Hamra', 'ar' => 'الحمرا'],
                    ['en' => 'Sin El Fil', 'ar' => 'سن الفيل'],
                    ['en' => 'Haret Hreik', 'ar' => 'حارة حريك'],
                    ['en' => 'Bir Abed', 'ar' => 'بير العبد'],
                    ['en' => 'Basta', 'ar' => 'البسطة'],
                    ['en' => 'Dahieh', 'ar' => 'الضاحية'],
                    ['en' => 'Ouzai', 'ar' => 'الأوزاعي'],
                    ['en' => 'Tariq El Jdideh', 'ar' => 'طريق الجديدة'],
                    ['en' => 'Mazraa', 'ar' => 'المزرعة'],
                    ['en' => 'Ain El Mreisseh', 'ar' => 'عين المريسة'],
                    ['en' => 'Manara', 'ar' => 'المنارة'],
                    ['en' => 'Raouche', 'ar' => 'الروشة'],
                    ['en' => 'Ras Beirut', 'ar' => 'رأس بيروت'],
                    ['en' => 'Sodeco', 'ar' => 'سوديكو'],
                    ['en' => 'Gemmayzeh', 'ar' => 'الجميزة'],
                    ['en' => 'Achrafieh', 'ar' => 'الأشرفية'],
                    ['en' => 'Tabaris', 'ar' => 'تباريز'],
                    ['en' => 'Mathaf', 'ar' => 'المتحف'],
                    ['en' => 'Qasqas', 'ar' => 'قصقص'],
                    ['en' => 'Zokak El Blatt', 'ar' => 'زقاق البلاط'],
                    ['en' => 'Mar Elias', 'ar' => 'مار إلياس'],
                    ['en' => 'Kaskas', 'ar' => 'كركاس'],
                    ['en' => 'Siyyad', 'ar' => 'الصياد'],
                    ['en' => 'Furn El Chebbak', 'ar' => 'فرن الشباك'],
                    ['en' => 'Jnah', 'ar' => 'الجناح'],
                    ['en' => 'Khalde', 'ar' => 'خلدة'],
                    ['en' => 'Chiyah', 'ar' => 'الشياح'],
                    ['en' => 'Hazmieh', 'ar' => 'الحازمية'],
                    ['en' => 'Dekwaneh', 'ar' => 'الدكوانة'],
                    ['en' => 'Baabda', 'ar' => 'بعبدا'],
                    ['en' => 'Sabra', 'ar' => 'صبرا'],
                    ['en' => 'Tariq El Matar', 'ar' => 'طريق المطار'],
                    ['en' => 'Karantina', 'ar' => 'الكرنتينا'],
                    ['en' => 'Burj Abi Haidar', 'ar' => 'برج أبي حيدر'],
                    ['en' => 'Ain El Remmaneh', 'ar' => 'عين الرمانة'],
                    ['en' => 'Badaro', 'ar' => 'بدارو'],
                    ['en' => 'Furn El Hayek', 'ar' => 'فرن الحايك'],
                    ['en' => 'Horch Tabet', 'ar' => 'حرش تابت'],
                    ['en' => 'Mar Mikhael', 'ar' => 'مار مخايل'],
                    ['en' => 'Bourj Hammoud', 'ar' => 'برج حمود'],
                    ['en' => 'Bourj El Barajneh', 'ar' => 'برج البراجنة'],
                    ['en' => 'Talet El Khayat', 'ar' => 'تلة الخياط'],
                    ['en' => 'Salim Slam', 'ar' => 'سليم سلام'],
                    ['en' => 'Bechara El Khoury', 'ar' => 'بشارة الخوري'],
                    ['en' => 'Charles Helou', 'ar' => 'شارل الحلو'],
                    ['en' => 'Jeitaoui', 'ar' => 'الجعيتاوي'],
                    ['en' => 'Monot', 'ar' => 'مونوت'],
                    ['en' => 'Clemenceau', 'ar' => 'كليمنصو'],
                    ['en' => 'Downtown Beirut', 'ar' => 'وسط بيروت'],
                    ['en' => 'Saifi Village', 'ar' => 'قرية الصيفي'],
                    ['en' => 'Sodeco Square', 'ar' => 'ساحة السوديكو'],
                    ['en' => 'Mathaf National Museum', 'ar' => 'متحف بيروت الوطني'],
                    ['en' => 'Fakhr El-Din Street', 'ar' => 'شارع فخر الدين'],
                    ['en' => 'Horch Beirut', 'ar' => 'حرش بيروت'],
                    ['en' => 'Sassine Square', 'ar' => 'ساحة ساسين'],
                    ['en' => 'El Cola', 'ar' => 'الكولا'],
                    ['en' => 'Barbir', 'ar' => 'الباربير'],
                    ['en' => 'Tayouneh', 'ar' => 'الطّيونة'],
                    ['en' => 'Rihaniyeh', 'ar' => 'الريحانية'],
                    ['en' => 'Airport Highway', 'ar' => 'أوتوستراد المطار'],
                    ['en' => 'Jisr El Basha', 'ar' => 'جسر الباشا'],
                    ['en' => 'Hazmieh New', 'ar' => 'الحازمية الجديدة'],
                    ['en' => 'Sfeir', 'ar' => 'صفير'],
                    ['en' => 'Shiyah South', 'ar' => 'الشياح الجنوبي'],
                ],
            ],
            [
                'en' => 'Baabda',
                'ar' => 'بعبدا',
                'areas' => [
                    ['en' => 'Baabda Main', 'ar' => 'بعبدا الرئيسية'],
                    ['en' => 'Hadath', 'ar' => 'حدث'],
                    ['en' => 'Hazmieh', 'ar' => 'الحازمية'],
                    ['en' => 'Yarzeh', 'ar' => 'يرزة'],
                    ['en' => 'Louaize', 'ar' => 'اللويزة'],
                    ['en' => 'Jamhour', 'ar' => 'جمهور'],
                    ['en' => 'Fanar', 'ar' => 'فنار'],
                    ['en' => 'Dekwaneh', 'ar' => 'الدكوانة'],
                    ['en' => 'Choueifat North', 'ar' => 'الشويفات الشمالية'],
                    ['en' => 'Ain Najm', 'ar' => 'عين نجم'],
                    ['en' => 'Monteverde', 'ar' => 'مونتيفيردي'],
                    ['en' => 'Qornet El Hamra', 'ar' => 'قرنة الحمرا'],
                    ['en' => 'Araya', 'ar' => 'عرايا'],
                    ['en' => 'Broummana Border', 'ar' => 'حدود برمانا'],
                    ['en' => 'Ain Saadeh', 'ar' => 'عين سعادة'],
                    ['en' => 'Bsalim', 'ar' => 'بصاليم'],
                    ['en' => 'Roumieh', 'ar' => 'رومية'],
                    ['en' => 'Mansourieh', 'ar' => 'المنصورية'],
                    ['en' => 'Beit Mery South', 'ar' => 'بيت مري الجنوبية'],
                    ['en' => 'Ain El Remmaneh', 'ar' => 'عين الرمانة'],
                    ['en' => 'Furn El Chebbak', 'ar' => 'فرن الشباك'],
                    ['en' => 'Jisr El Basha', 'ar' => 'جسر الباشا'],
                    ['en' => 'Kfarshima', 'ar' => 'كفرشيما'],
                    ['en' => 'Khaldeh Border', 'ar' => 'حدود خلدة'],
                    ['en' => 'Haret El Set', 'ar' => 'حارة الست'],
                    ['en' => 'Siyyad', 'ar' => 'الصياد'],
                    ['en' => 'Baabda Palace Area', 'ar' => 'منطقة القصر الجمهوري'],
                    ['en' => 'Mechref', 'ar' => 'مشفرف'],
                    ['en' => 'Bchamoun Edge', 'ar' => 'طرف بشامون'],
                    ['en' => 'Saksakiyeh', 'ar' => 'السكسكية'],
                    ['en' => 'Wadi Chahrour', 'ar' => 'وادي شحرور'],
                    ['en' => 'Ain El Tineh (Baabda)', 'ar' => 'عين التينة (بعبدا)'],
                    ['en' => 'Baabda Highway', 'ar' => 'أوتوستراد بعبدا'],
                    ['en' => 'Baabda Old Souk', 'ar' => 'سوق بعبدا القديم'],
                    ['en' => 'Salim Salam Extension', 'ar' => 'امتداد سليم سلام'],
                    ['en' => 'Talet Baabda', 'ar' => 'تلة بعبدا'],
                    ['en' => 'Baabda Market', 'ar' => 'سوق بعبدا'],
                ],
            ],


            [
                'en' => 'Aley',
                'ar' => 'عاليه',
                'areas' => [
                    ['en' => 'Aley Downtown', 'ar' => 'وسط عاليه'],
                    ['en' => 'Souk Aley', 'ar' => 'سوق عاليه'],
                    ['en' => 'Ain El Saydeh', 'ar' => 'عين السيدة'],
                    ['en' => 'Ain El Remmaneh - Aley', 'ar' => 'عين الرمانة - عاليه'],
                    ['en' => 'Ain Dara', 'ar' => 'عين دارة'],
                    ['en' => 'Bhamdoun El Mhatta', 'ar' => 'بحمدون المحطة'],
                    ['en' => 'Bhamdoun El Dayaa', 'ar' => 'بحمدون الضيعة'],
                    ['en' => 'Souk El Gharb', 'ar' => 'سوق الغرب'],
                    ['en' => 'Qmatiyeh', 'ar' => 'قمطية'],
                    ['en' => 'Abey', 'ar' => 'عبيه'],
                    ['en' => 'Ain Anoub', 'ar' => 'عين عنوب'],
                    ['en' => 'Baissour', 'ar' => 'بيصور'],
                    ['en' => 'Bayssour Heights', 'ar' => 'مرتفعات بيصور'],
                    ['en' => 'Kfarmatta', 'ar' => 'كفرمتى'],
                    ['en' => 'Remhala', 'ar' => 'رومحالا'],
                    ['en' => 'Chartoun', 'ar' => 'شارتون'],
                    ['en' => 'Bserrine', 'ar' => 'بسرين'],
                    ['en' => 'Kaifoun', 'ar' => 'كيفون'],
                    ['en' => 'Aghmid', 'ar' => 'اغميد'],
                    ['en' => 'Ras El Jabal', 'ar' => 'رأس الجبل'],
                    ['en' => 'Ain Ksour', 'ar' => 'عين كسور'],
                    ['en' => 'Shwayfat Heights', 'ar' => 'مرتفعات شويفات'],
                    ['en' => 'Btater', 'ar' => 'بتاتر'],
                    ['en' => 'Majdlaya - Aley', 'ar' => 'مجدليا - عاليه'],
                    ['en' => 'Kfarnabrakh', 'ar' => 'كفرنبرخ'],
                    ['en' => 'Serjbal', 'ar' => 'سرجبال'],
                    ['en' => 'Keyfoun El Tahta', 'ar' => 'كيفون التحتا'],
                    ['en' => 'Kaifoun Heights', 'ar' => 'مرتفعات كيفون'],
                    ['en' => 'Aaramoun - Aley', 'ar' => 'عرمون - عاليه'],
                    ['en' => 'Chemlan', 'ar' => 'شملان'],
                    ['en' => 'Mreijat - Aley', 'ar' => 'مريجات - عاليه'],
                    ['en' => 'Ain Zhalta Road', 'ar' => 'طريق عين زحلتا'],
                    ['en' => 'Araya - Aley', 'ar' => 'عرَيّا - عاليه'],
                    ['en' => 'Jamhour - Aley Sector', 'ar' => 'الجمهور - قطاع عاليه'],
                    ['en' => 'Ainab', 'ar' => 'عيناب'],
                    ['en' => 'Rimah', 'ar' => 'ريماح'],
                    ['en' => 'Ras El Metn Border', 'ar' => 'حدود رأس المتن'],
                ],
            ],


            [
                'en' => 'Choueifat',
                'ar' => 'الشويفات',
                'areas' => [
                    ['en' => 'Choueifat Main', 'ar' => 'الشويفات الرئيسية'],
                    ['en' => 'Khaldeh', 'ar' => 'خلدة'],
                    ['en' => 'Wadi Chahrour', 'ar' => 'وادي شحرور'],
                    ['en' => 'Aaramoun Border', 'ar' => 'حدود عرمون'],
                    ['en' => 'Kfarchima Border', 'ar' => 'حدود كفرشيما'],
                    ['en' => 'Choueifat Industrial Zone', 'ar' => 'المنطقة الصناعية في الشويفات'],
                    ['en' => 'Choueifat Airport Road', 'ar' => 'طريق المطار - الشويفات'],
                    ['en' => 'Mouarjat', 'ar' => 'المورجات'],
                    ['en' => 'Choueifat Cemetery Area', 'ar' => 'منطقة المقبرة - الشويفات'],
                    ['en' => 'Ain Anoub Border', 'ar' => 'حدود عين عنوب'],
                    ['en' => 'Mar Roukoz Hill', 'ar' => 'تلة مار روكز'],
                    ['en' => 'Ras El Jabal', 'ar' => 'رأس الجبل'],
                    ['en' => 'Haret El Saiyad', 'ar' => 'حارة الصياد'],
                    ['en' => 'Ain El Saydeh', 'ar' => 'عين السيدة'],
                    ['en' => 'Sahl', 'ar' => 'السهل'],
                    ['en' => 'Kfarselwan Border', 'ar' => 'حدود كفرسلوان'],
                    ['en' => 'Madwar', 'ar' => 'مدور'],
                    ['en' => 'Haret El Dekwaneh', 'ar' => 'حارة الدكوانة'],
                    ['en' => 'Ommara', 'ar' => 'عمارة'],
                    ['en' => 'Karma', 'ar' => 'كرمة'],
                    ['en' => 'Ain El Rihaneh Border', 'ar' => 'حدود عين الريحانة'],
                    ['en' => 'Choueifat Schools Area', 'ar' => 'منطقة المدارس - الشويفات'],
                    ['en' => 'Safa Hill', 'ar' => 'تلة الصفا'],
                    ['en' => 'New Choueifat', 'ar' => 'الشويفات الجديدة'],
                    ['en' => 'Choueifat Market', 'ar' => 'سوق الشويفات'],
                    ['en' => 'Ain El Saydeh Upper', 'ar' => 'عين السيدة العليا'],
                    ['en' => 'Mar Takla', 'ar' => 'مار تقلا'],
                    ['en' => 'Airport View', 'ar' => 'مطل المطار'],
                    ['en' => 'Daraya Border', 'ar' => 'حدود داريا'],
                    ['en' => 'Salim Salam Edge', 'ar' => 'طرف سليم سلام'],
                ],
            ],


            [
                'en' => 'Jounieh',
                'ar' => 'جونية',
                'areas' => [
                    ['en' => 'Old Souk', 'ar' => 'السوق القديم'],
                    ['en' => 'Kaslik', 'ar' => 'كسليك'],
                    ['en' => 'Haret Sakher', 'ar' => 'حارة صخر'],
                    ['en' => 'Maaysrah', 'ar' => 'معيصرة'],
                    ['en' => 'Adma Border', 'ar' => 'حدود أدما'],
                    ['en' => 'Haret Salem', 'ar' => 'حارة سالم'],
                    ['en' => 'Maalqa', 'ar' => 'معلقة'],
                    ['en' => 'Kfar Yassine Border', 'ar' => 'حدود كفر ياسين'],
                    ['en' => 'Sarba', 'ar' => 'سربا'],
                    ['en' => 'Tabarja Border', 'ar' => 'حدود طبرجا'],
                    ['en' => 'Jounieh Marina', 'ar' => 'مارينا جونية'],
                    ['en' => 'Casino du Liban Area', 'ar' => 'منطقة كازينو لبنان'],
                    ['en' => 'Upper Jounieh', 'ar' => 'جونية العليا'],
                    ['en' => 'St. Louis Area', 'ar' => 'منطقة سانت لويس'],
                    ['en' => 'Notre Dame De Louaize', 'ar' => 'سيدة اللويزة'],
                    ['en' => 'Saqiyet al-Kheit', 'ar' => 'ساقية الخيط'],
                    ['en' => 'Jeita Border', 'ar' => 'حدود جعيتا'],
                    ['en' => 'Harissa Base', 'ar' => 'سفح حريصا'],
                    ['en' => 'Ghazir Border', 'ar' => 'حدود غزير'],
                    ['en' => 'Sea Road', 'ar' => 'طريق البحر'],
                    ['en' => 'Boulevard Area', 'ar' => 'منطقة البولفار'],
                    ['en' => 'Jounieh Highway', 'ar' => 'أوتوستراد جونية'],
                    ['en' => 'Blat Border', 'ar' => 'حدود بلاط'],
                    ['en' => 'Jounieh Stadium Area', 'ar' => 'منطقة ملعب جونية'],
                    ['en' => 'Near Hospital Notre Dame', 'ar' => 'بالقرب من مستشفى سيدة'],
                    ['en' => 'Mansourieh El Metn Border', 'ar' => 'حدود المنصورية'],
                    ['en' => 'College Des Freres Area', 'ar' => 'منطقة مدرسة الفرير'],
                    ['en' => 'Main Market', 'ar' => 'السوق الرئيسي'],
                    ['en' => 'Mar Takla Jounieh', 'ar' => 'مار تقلا جونية'],
                    ['en' => 'Basilique Area', 'ar' => 'منطقة البازيليك'],
                ],
            ],
            [
                'en' => 'Zouk Mosbeh',
                'ar' => 'ذوق مصبح',
                'areas' => [
                    ['en' => 'Zouk Main Road', 'ar' => 'طريق الذوق الرئيسية'],
                    ['en' => 'NDU Area', 'ar' => 'منطقة جامعة سيدة اللويزة'],
                    ['en' => 'Zouk Highway', 'ar' => 'أوتوستراد الذوق'],
                    ['en' => 'Industrial Zone', 'ar' => 'المنطقة الصناعية'],
                    ['en' => 'St. Charbel Area', 'ar' => 'منطقة مار شربل'],
                    ['en' => 'Upper Zouk', 'ar' => 'الذوق الفوقا'],
                    ['en' => 'Zouk Seaside', 'ar' => 'ذوق البحر'],
                    ['en' => 'Zouk Entrance', 'ar' => 'مدخل الذوق'],
                    ['en' => 'Near Zouk Power Plant', 'ar' => 'بالقرب من محطة الكهرباء'],
                    ['en' => 'Al Nahda Street', 'ar' => 'شارع النهضة'],
                    ['en' => 'Zouk Mosbeh Square', 'ar' => 'ساحة ذوق مصبح'],
                    ['en' => 'Louaize Border', 'ar' => 'حدود اللويزة'],
                    ['en' => 'Monastery Zone', 'ar' => 'منطقة الدير'],
                    ['en' => 'ABC Dbayeh Border', 'ar' => 'حدود إيه بي سي ضبية'],
                    ['en' => 'Jeita Intersection', 'ar' => 'مفترق جعيتا'],
                    ['en' => 'Naccache Border', 'ar' => 'حدود النقاش'],
                    ['en' => 'Stadium Road', 'ar' => 'طريق الملعب'],
                    ['en' => 'Adonis Border', 'ar' => 'حدود أدونيس'],
                    ['en' => 'Zouk Hospital Area', 'ar' => 'منطقة مستشفى الذوق'],
                    ['en' => 'Residential Blocs', 'ar' => 'المجمعات السكنية'],
                    ['en' => 'Supermarket Strip', 'ar' => 'منطقة السوبرماركتات'],
                    ['en' => 'Fanar Edge', 'ar' => 'طرف الفنار'],
                    ['en' => 'Zouk Mosbeh Church', 'ar' => 'كنيسة ذوق مصبح'],
                    ['en' => 'Bakery Area', 'ar' => 'منطقة الأفران'],
                    ['en' => 'Fire Station Area', 'ar' => 'منطقة مركز الدفاع المدني'],
                    ['en' => 'Mall Vicinity', 'ar' => 'محيط المركز التجاري'],
                    ['en' => 'Gated Communities', 'ar' => 'المجمعات المغلقة'],
                    ['en' => 'Road to Kaslik', 'ar' => 'الطريق إلى كسليك'],
                    ['en' => 'Jounieh Border', 'ar' => 'حدود جونية'],
                    ['en' => 'Main Zouk Souk', 'ar' => 'سوق الذوق الرئيسي'],
                ],
            ],
            [
                'en' => 'Dbayeh',
                'ar' => 'ضبية',
                'areas' => [
                    ['en' => 'Dbayeh Highway', 'ar' => 'أوتوستراد ضبية'],
                    ['en' => 'ABC Mall Area', 'ar' => 'منطقة مول إيه بي سي'],
                    ['en' => 'Waterfront City', 'ar' => 'الواجهة البحرية'],
                    ['en' => 'Dbayeh Industrial Zone', 'ar' => 'المنطقة الصناعية في ضبية'],
                    ['en' => 'Naccache Border', 'ar' => 'حدود النقاش'],
                    ['en' => 'Mar Takla Area', 'ar' => 'منطقة مار تقلا'],
                    ['en' => 'Dbayeh Seaside', 'ar' => 'ضبية البحرية'],
                    ['en' => 'Dbayeh Police Station Area', 'ar' => 'منطقة مخفر ضبية'],
                    ['en' => 'Le Mall Dbayeh Area', 'ar' => 'منطقة لو مول ضبية'],
                    ['en' => 'Antelias Border', 'ar' => 'حدود انطلياس'],
                    ['en' => 'Dbayeh Marina', 'ar' => 'مرسى ضبية'],
                    ['en' => 'Rabweh Border', 'ar' => 'حدود الربوة'],
                    ['en' => 'Dbayeh Evangelical Center', 'ar' => 'مركز الإنجيل ضبية'],
                    ['en' => 'Dbayeh Camp Area', 'ar' => 'منطقة مخيم ضبية'],
                    ['en' => 'Old Dbayeh', 'ar' => 'ضبية القديمة'],
                    ['en' => 'Armenian Quarter', 'ar' => 'الحي الأرمني'],
                    ['en' => 'Upper Dbayeh', 'ar' => 'ضبية الفوقا'],
                    ['en' => 'Hospital Vicinity', 'ar' => 'محيط المستشفى'],
                    ['en' => 'St. Rita Area', 'ar' => 'منطقة سانت ريتا'],
                    ['en' => 'Fanar Road End', 'ar' => 'نهاية طريق الفنار'],
                    ['en' => 'Nahr El Kalb Border', 'ar' => 'حدود نهر الكلب'],
                    ['en' => 'Residential Dbayeh', 'ar' => 'ضبية السكنية'],
                    ['en' => 'Dbayeh Schools Zone', 'ar' => 'منطقة المدارس في ضبية'],
                    ['en' => 'Dbayeh Church Square', 'ar' => 'ساحة كنيسة ضبية'],
                    ['en' => 'Tech Hub Dbayeh', 'ar' => 'منطقة التقنية في ضبية'],
                    ['en' => 'Dbayeh Bridge Area', 'ar' => 'منطقة جسر ضبية'],
                    ['en' => 'Dbayeh Exit 7', 'ar' => 'مخرج ضبية 7'],
                    ['en' => 'Dbayeh Fishermen Port', 'ar' => 'ميناء صيادي ضبية'],
                    ['en' => 'Dbayeh Gas Station Strip', 'ar' => 'منطقة محطات البنزين'],
                    ['en' => 'Dbayeh Army Base Area', 'ar' => 'منطقة ثكنة ضبية'],
                ],
            ],
            [
                'en' => 'Broummana',
                'ar' => 'برمانا',
                'areas' => [
                    ['en' => 'Main Street', 'ar' => 'الشارع الرئيسي'],
                    ['en' => 'Broummana High School Area', 'ar' => 'منطقة مدرسة برمانا'],
                    ['en' => 'Upper Broummana', 'ar' => 'برمانا العليا'],
                    ['en' => 'Lower Broummana', 'ar' => 'برمانا السفلى'],
                    ['en' => 'Al Midan', 'ar' => 'الميدان'],
                    ['en' => 'Qasr Broummana', 'ar' => 'قصر برمانا'],
                    ['en' => 'Ain El Sihha', 'ar' => 'عين الصحة'],
                    ['en' => 'Hotel Area', 'ar' => 'منطقة الفنادق'],
                    ['en' => 'Broummana Club Area', 'ar' => 'منطقة نادي برمانا'],
                    ['en' => 'Ain El Jaouze', 'ar' => 'عين الجوزة'],
                    ['en' => 'Church District', 'ar' => 'حي الكنيسة'],
                    ['en' => 'Al Hadath Street', 'ar' => 'شارع الحدث'],
                    ['en' => 'Broummana Souk', 'ar' => 'سوق برمانا'],
                    ['en' => 'Broummana Municipality Zone', 'ar' => 'منطقة البلدية'],
                    ['en' => 'Al Saydeh Area', 'ar' => 'منطقة السيدة'],
                    ['en' => 'Jisr Broummana', 'ar' => 'جسر برمانا'],
                    ['en' => 'Broummana Gardens', 'ar' => 'حدائق برمانا'],
                    ['en' => 'El Jabal Edge', 'ar' => 'طرف الجبل'],
                    ['en' => 'Bellevue', 'ar' => 'بلفو'],
                    ['en' => 'Chahine', 'ar' => 'شاهين'],
                    ['en' => 'Sodetel Area', 'ar' => 'منطقة سوديتل'],
                    ['en' => 'Pine Zone', 'ar' => 'منطقة الصنوبر'],
                    ['en' => 'Mansourieh Border', 'ar' => 'حدود المنصورية'],
                    ['en' => 'Baabdat View', 'ar' => 'مطل بعبدات'],
                    ['en' => 'Saydet El Jabal', 'ar' => 'سيدة الجبل'],
                    ['en' => 'Ain Tineh', 'ar' => 'عين التينة'],
                    ['en' => 'Hilltop Residences', 'ar' => 'مساكن التلة'],
                    ['en' => 'Forest View', 'ar' => 'مطل الغابة'],
                    ['en' => 'Old Broummana', 'ar' => 'برمانا القديمة'],
                    ['en' => 'Clemenceau Villas', 'ar' => 'فلل كليمنصو'],
                ],
            ],
            [
                'en' => 'Beit Mery',
                'ar' => 'بيت مري',
                'areas' => [
                    ['en' => 'Beit Mery Main Road', 'ar' => 'الطريق الرئيسي'],
                    ['en' => 'Beit Mery Municipality', 'ar' => 'بلدية بيت مري'],
                    ['en' => 'Mar Elias Monastery', 'ar' => 'دير مار الياس'],
                    ['en' => 'Jisr Beit Mery', 'ar' => 'جسر بيت مري'],
                    ['en' => 'Qornet Beit Mery', 'ar' => 'قرنة بيت مري'],
                    ['en' => 'Dayr El Kalaa', 'ar' => 'دير القلعة'],
                    ['en' => 'Ain El Saydeh', 'ar' => 'عين السيدة'],
                    ['en' => 'Beit Mery Souk', 'ar' => 'سوق بيت مري'],
                    ['en' => 'Zaarour View', 'ar' => 'مطل الزعرور'],
                    ['en' => 'Antelias Border', 'ar' => 'حدود انطلياس'],
                    ['en' => 'Mansourieh Border', 'ar' => 'حدود المنصورية'],
                    ['en' => 'Al Kroum', 'ar' => 'الكروم'],
                    ['en' => 'Garden Hill', 'ar' => 'تلة الحديقة'],
                    ['en' => 'Al Marj', 'ar' => 'المرج'],
                    ['en' => 'Saydet Beit Mery', 'ar' => 'سيدة بيت مري'],
                    ['en' => 'Ecole Al Jabal', 'ar' => 'مدرسة الجبل'],
                    ['en' => 'Saydet El Kalaa', 'ar' => 'سيدة القلعة'],
                    ['en' => 'Nabeh Al Slaib', 'ar' => 'نبع الصليب'],
                    ['en' => 'El Ramiyeh', 'ar' => 'الرّامية'],
                    ['en' => 'Beit Mery Hills', 'ar' => 'تلال بيت مري'],
                    ['en' => 'Arz Beit Mery', 'ar' => 'أرز بيت مري'],
                    ['en' => 'Eastern Gate', 'ar' => 'البوابة الشرقية'],
                    ['en' => 'Al Midan', 'ar' => 'الميدان'],
                    ['en' => 'Villa Zone', 'ar' => 'منطقة الفيلات'],
                    ['en' => 'Beit Mery Theater', 'ar' => 'مسرح بيت مري'],
                    ['en' => 'Rihaniyeh Road', 'ar' => 'طريق الريحانية'],
                    ['en' => 'Bdadoun Border', 'ar' => 'حدود بحدود'],
                    ['en' => 'Jamhour View', 'ar' => 'مطل الجمهور'],
                    ['en' => 'Beit Mery Valley', 'ar' => 'وادي بيت مري'],
                    ['en' => 'El Qalaa Ridge', 'ar' => 'تلة القلعة'],
                ],
            ],
            [
                'en' => 'Bikfaya',
                'ar' => 'بكفيا',
                'areas' => [
                    ['en' => 'Bikfaya Main Road', 'ar' => 'الطريق الرئيسي'],
                    ['en' => 'Ain El Kharroubeh', 'ar' => 'عين الخرّوبة'],
                    ['en' => 'Bikfaya Square', 'ar' => 'ساحة بكفيا'],
                    ['en' => 'Al Hadath Border', 'ar' => 'حدود الحدث'],
                    ['en' => 'Bikfaya Church Area', 'ar' => 'منطقة الكنيسة'],
                    ['en' => 'Mar Sassine', 'ar' => 'مار ساسين'],
                    ['en' => 'Bikfaya Old Souk', 'ar' => 'السوق القديم'],
                    ['en' => 'Pine Forest', 'ar' => 'غابة الصنوبر'],
                    ['en' => 'Mar Roukoz Valley', 'ar' => 'وادي مار روكز'],
                    ['en' => 'Saydet Bikfaya', 'ar' => 'سيدة بكفيا'],
                    ['en' => 'Ain El Jdeideh', 'ar' => 'عين الجديدة'],
                    ['en' => 'Sanawbar Street', 'ar' => 'شارع الصنوبر'],
                    ['en' => 'Al Midan', 'ar' => 'الميدان'],
                    ['en' => 'Upper Bikfaya', 'ar' => 'بكفيا العليا'],
                    ['en' => 'Lower Bikfaya', 'ar' => 'بكفيا السفلى'],
                    ['en' => 'Tallet Bikfaya', 'ar' => 'تلة بكفيا'],
                    ['en' => 'Bikfaya Villas Area', 'ar' => 'منطقة الفيلات'],
                    ['en' => 'Bikfaya Schools District', 'ar' => 'منطقة المدارس'],
                    ['en' => 'Jdeideh Border', 'ar' => 'حدود الجديدة'],
                    ['en' => 'Ain Al Saydeh', 'ar' => 'عين السيدة'],
                    ['en' => 'Jisr Al Arz', 'ar' => 'جسر الأرز'],
                    ['en' => 'Bikfaya Municipality Area', 'ar' => 'منطقة البلدية'],
                    ['en' => 'Church Valley', 'ar' => 'وادي الكنيسة'],
                    ['en' => 'Kornet El Hamra', 'ar' => 'قرنة الحمرا'],
                    ['en' => 'Bikfaya Scouts Center', 'ar' => 'مركز الكشافة'],
                    ['en' => 'Garden Hill', 'ar' => 'تلة الحديقة'],
                    ['en' => 'Saydet El Biya', 'ar' => 'سيدة البيئة'],
                    ['en' => 'Beit Chabab Border', 'ar' => 'حدود بيت شباب'],
                    ['en' => 'Bikfaya Maronite College', 'ar' => 'كلية الموارنة'],
                    ['en' => 'Ras El Qalaa', 'ar' => 'رأس القلعة'],
                ],
            ],
            [
                'en' => 'Hazmieh',
                'ar' => 'الحازمية',
                'areas' => [
                    ['en' => 'Mar Takla', 'ar' => 'مار تقلا'],
                    ['en' => 'Hazmieh Square', 'ar' => 'ساحة الحازمية'],
                    ['en' => 'Baabda Road', 'ar' => 'طريق بعبدا'],
                    ['en' => 'Hazmieh Highway', 'ar' => 'أوتوستراد الحازمية'],
                    ['en' => 'New Hazmieh', 'ar' => 'الحازمية الجديدة'],
                    ['en' => 'Jisr El Basha Border', 'ar' => 'حدود جسر الباشا'],
                    ['en' => 'Saydet Hazmieh', 'ar' => 'سيدة الحازمية'],
                    ['en' => 'Hospital Area', 'ar' => 'منطقة المستشفى'],
                    ['en' => 'Daher Sarba', 'ar' => 'ضهر صربا'],
                    ['en' => 'Hazmieh Mall Area', 'ar' => 'منطقة مول الحازمية'],
                    ['en' => 'Karantina Border', 'ar' => 'حدود الكرنتينا'],
                    ['en' => 'Mansourieh Border', 'ar' => 'حدود المنصورية'],
                    ['en' => 'Rihaniyeh View', 'ar' => 'مطل الريحانية'],
                    ['en' => 'Saydet Al Intikal', 'ar' => 'سيدة الانتقال'],
                    ['en' => 'Jesuit School Area', 'ar' => 'منطقة مدرسة اليسوعيين'],
                    ['en' => 'Hazmieh Church District', 'ar' => 'حي الكنيسة'],
                    ['en' => 'Abraj Center', 'ar' => 'سنتر الأبراج'],
                    ['en' => 'Bank Street', 'ar' => 'شارع المصارف'],
                    ['en' => 'Ministerial Complex', 'ar' => 'مجمع الوزارات'],
                    ['en' => 'Al Midan', 'ar' => 'الميدان'],
                    ['en' => 'Hazmieh Industrial Area', 'ar' => 'المنطقة الصناعية'],
                    ['en' => 'El Nahr Street', 'ar' => 'شارع النهر'],
                    ['en' => 'Martyrs’ Park', 'ar' => 'حديقة الشهداء'],
                    ['en' => 'Sporting Center', 'ar' => 'المركز الرياضي'],
                    ['en' => 'Hazmieh Villas Zone', 'ar' => 'منطقة الفيلات'],
                    ['en' => 'Ain Al Saydeh', 'ar' => 'عين السيدة'],
                    ['en' => 'Chiyah Border', 'ar' => 'حدود الشياح'],
                    ['en' => 'Tayouneh Road', 'ar' => 'طريق الطيونة'],
                    ['en' => 'Beit Mery Border', 'ar' => 'حدود بيت مري'],
                    ['en' => 'Saydeh Junction', 'ar' => 'مفرق السيدة'],
                ],
            ],
            [
                'en' => 'Tripoli',
                'ar' => 'طرابلس',
                'areas' => [
                    ['en' => 'Mina', 'ar' => 'الميناء'],
                    ['en' => 'Tal', 'ar' => 'التل'],
                    ['en' => 'Zahriyeh', 'ar' => 'الزهرية'],
                    ['en' => 'Qoubbeh', 'ar' => 'القبة'],
                    ['en' => 'Abou Samra', 'ar' => 'أبو سمرا'],
                    ['en' => 'Ashrafieh', 'ar' => 'الأشرفية'],
                    ['en' => 'Azmi Street', 'ar' => 'شارع عزمي'],
                    ['en' => 'Maarad', 'ar' => 'المعرض'],
                    ['en' => 'Dahr Al Maghar', 'ar' => 'ضهر المغر'],
                    ['en' => 'Riad El Solh', 'ar' => 'رياض الصلح'],
                    ['en' => 'Boulevard', 'ar' => 'البولفار'],
                    ['en' => 'Dahr Al Ain', 'ar' => 'ضهر العين'],
                    ['en' => 'Souk Al Haraj', 'ar' => 'سوق الحراج'],
                    ['en' => 'Kobbeh Hospital Area', 'ar' => 'منطقة مستشفى القبة'],
                    ['en' => 'Bab El Ramel', 'ar' => 'باب الرمل'],
                    ['en' => 'Bab El Tabbaneh', 'ar' => 'باب التبانة'],
                    ['en' => 'Jabal Mohsen', 'ar' => 'جبل محسن'],
                    ['en' => 'Mankoubin', 'ar' => 'المنكوبين'],
                    ['en' => 'Koura Border', 'ar' => 'حدود الكورة'],
                    ['en' => 'Ras Maska Border', 'ar' => 'حدود رأس مسقا'],
                    ['en' => 'Al Tallawiyyin', 'ar' => 'الطلاويين'],
                    ['en' => 'Old City', 'ar' => 'المدينة القديمة'],
                    ['en' => 'Tripoli Castle Area', 'ar' => 'منطقة قلعة طرابلس'],
                    ['en' => 'Dahr El Qamar', 'ar' => 'ضهر القمر'],
                    ['en' => 'New Mina', 'ar' => 'الميناء الجديدة'],
                    ['en' => 'Ain El Mreisseh', 'ar' => 'عين المريسة'],
                    ['en' => 'Beddawi', 'ar' => 'البداوي'],
                    ['en' => 'Bahsas', 'ar' => 'البحصاص'],
                    ['en' => 'Shalfeh', 'ar' => 'شلفة'],
                    ['en' => 'Hay El Nour', 'ar' => 'حي النور'],
                ],
            ],
            [
                'en' => 'Zgharta',
                'ar' => 'زغرتا',
                'areas' => [
                    ['en' => 'Zgharta Main', 'ar' => 'زغرتا الرئيسية'],
                    ['en' => 'Ehden', 'ar' => 'إهدن'],
                    ['en' => 'Kfarhata', 'ar' => 'كفرحاتا'],
                    ['en' => 'Ain El Tour', 'ar' => 'عين التور'],
                    ['en' => 'Miriata', 'ar' => 'مرياطة'],
                    ['en' => 'Kfaryachit', 'ar' => 'كفرياشيت'],
                    ['en' => 'Ardeh', 'ar' => 'أرده'],
                    ['en' => 'Rachiine', 'ar' => 'رشعين'],
                    ['en' => 'Sebhel', 'ar' => 'سبعل'],
                    ['en' => 'Iaal', 'ar' => 'إيعال'],
                    ['en' => 'Harf Ardeh', 'ar' => 'حرف أرده'],
                    ['en' => 'Mazraat Zgharta', 'ar' => 'مزرعة زغرتا'],
                    ['en' => 'Ain Ekrine', 'ar' => 'عين إكرين'],
                    ['en' => 'Kfarzina', 'ar' => 'كفرزينا'],
                    ['en' => 'Mezher', 'ar' => 'مزر'],
                    ['en' => 'Haret El Bayader', 'ar' => 'حارة البيادر'],
                    ['en' => 'Hay El Nahda', 'ar' => 'حي النهضة'],
                    ['en' => 'Mar Sarkis', 'ar' => 'مار سركيس'],
                    ['en' => 'Tallet Sebhel', 'ar' => 'تلة سبعل'],
                    ['en' => 'Kfarhata Heights', 'ar' => 'علية كفرحاتا'],
                    ['en' => 'Zgharta Souk', 'ar' => 'سوق زغرتا'],
                    ['en' => 'Mansoura', 'ar' => 'المنصورة'],
                    ['en' => 'Mar Gerges', 'ar' => 'مار جرجس'],
                    ['en' => 'Saint Doumit', 'ar' => 'مار دوميط'],
                    ['en' => 'Ain Majdal', 'ar' => 'عين مجدل'],
                    ['en' => 'Mazraat Sahrieh', 'ar' => 'مزرعة صحرا'],
                    ['en' => 'Hadath Zgharta', 'ar' => 'حدث زغرتا'],
                    ['en' => 'Nabi Yousef', 'ar' => 'النبي يوسف'],
                    ['en' => 'Mazraat Zgharta Heights', 'ar' => 'علية مزرعة زغرتا'],
                    ['en' => 'Deir Mar Antonios', 'ar' => 'دير مار انطونيوس'],
                ],
            ],
            [
                'en' => 'Bcharre',
                'ar' => 'بشري',
                'areas' => [
                    ['en' => 'Bcharre Main', 'ar' => 'بشري الرئيسية'],
                    ['en' => 'Qadisha Valley', 'ar' => 'وادي قاديشا'],
                    ['en' => 'Wadi Kannoubine', 'ar' => 'وادي قنوبين'],
                    ['en' => 'Mar Lichaa', 'ar' => 'مار ليشاع'],
                    ['en' => 'Hadath El Jebbeh', 'ar' => 'حدث الجبة'],
                    ['en' => 'Blawza', 'ar' => 'بلوزا'],
                    ['en' => 'Diman', 'ar' => 'الديمان'],
                    ['en' => 'Bazaoun', 'ar' => 'بزعون'],
                    ['en' => 'Ainata', 'ar' => 'عيناتا'],
                    ['en' => 'Tourza', 'ar' => 'طورزا'],
                    ['en' => 'Horsh Ehden', 'ar' => 'حرش إهدن'],
                    ['en' => 'Beqaasifrine', 'ar' => 'بقاعصفرين'],
                    ['en' => 'Aabdine', 'ar' => 'عبدين'],
                    ['en' => 'Bazoun Heights', 'ar' => 'علية بزعون'],
                    ['en' => 'Saint Saba', 'ar' => 'مار سابا'],
                    ['en' => 'Mar Gerges', 'ar' => 'مار جرجس'],
                    ['en' => 'Qarnayel', 'ar' => 'قرنايل'],
                    ['en' => 'Tallet Bcharre', 'ar' => 'تلة بشري'],
                    ['en' => 'Ain El Jawzeh', 'ar' => 'عين الجوزة'],
                    ['en' => 'Bcharre Souk', 'ar' => 'سوق بشري'],
                    ['en' => 'Mazraat Bcharre', 'ar' => 'مزرعة بشري'],
                    ['en' => 'Old Bcharre', 'ar' => 'بشري القديمة'],
                    ['en' => 'Wata Bcharre', 'ar' => 'وطى بشري'],
                    ['en' => 'Gibran Museum Area', 'ar' => 'منطقة متحف جبران'],
                    ['en' => 'Saydet Bcharre', 'ar' => 'سيدة بشري'],
                    ['en' => 'Mazraat El Saydeh', 'ar' => 'مزرعة السيدة'],
                    ['en' => 'Monastery District', 'ar' => 'حي الدير'],
                    ['en' => 'Ehden Road', 'ar' => 'طريق إهدن'],
                    ['en' => 'Sadd Bcharre', 'ar' => 'سد بشري'],
                    ['en' => 'Bcharre Heights', 'ar' => 'علية بشري'],
                ],
            ],
            [
                'en' => 'Koura (Amioun)',
                'ar' => 'الكورة – أميون',
                'areas' => [
                    ['en' => 'Amioun', 'ar' => 'أميون'],
                    ['en' => 'Deddeh', 'ar' => 'دده'],
                    ['en' => 'Kfarhazir', 'ar' => 'كفرحزير'],
                    ['en' => 'Batroumine', 'ar' => 'بطرام'],
                    ['en' => 'Anfeh', 'ar' => 'أنفه'],
                    ['en' => 'Kfarakka', 'ar' => 'كفرعقا'],
                    ['en' => 'Btouratij', 'ar' => 'بترتيج'],
                    ['en' => 'Ras Maska', 'ar' => 'رأس مسقا'],
                    ['en' => 'Kousba', 'ar' => 'كوسبا'],
                    ['en' => 'Enfeh Border', 'ar' => 'حدود انفه'],
                    ['en' => 'Bziza', 'ar' => 'بزيزا'],
                    ['en' => 'Majdel', 'ar' => 'مجذل'],
                    ['en' => 'Koura Highway', 'ar' => 'أوتوستراد الكورة'],
                    ['en' => 'Basloukit', 'ar' => 'بسلوقيت'],
                    ['en' => 'Jdayel Border', 'ar' => 'حدود جدايل'],
                    ['en' => 'Ain Al Delbeh', 'ar' => 'عين الدلبة'],
                    ['en' => 'Nakhleh', 'ar' => 'نخلة'],
                    ['en' => 'Mazraat Koura', 'ar' => 'مزرعة الكورة'],
                    ['en' => 'Bechmezzine', 'ar' => 'بشمزين'],
                    ['en' => 'Kfaraaka Heights', 'ar' => 'علية كفرعقا'],
                    ['en' => 'St. Simeon Monastery', 'ar' => 'دير مار سمعان'],
                    ['en' => 'Koura Industrial Zone', 'ar' => 'المنطقة الصناعية بالكورة'],
                    ['en' => 'Qalhat', 'ar' => 'قلحات'],
                    ['en' => 'Tripoli Border', 'ar' => 'حدود طرابلس'],
                    ['en' => 'Nabi Youchaa', 'ar' => 'النبي يوشع'],
                    ['en' => 'Koura University District', 'ar' => 'منطقة الجامعة'],
                    ['en' => 'Kfarballa', 'ar' => 'كفر بلا'],
                    ['en' => 'Ain El Jdeideh', 'ar' => 'عين الجديدة'],
                    ['en' => 'Jdayel View', 'ar' => 'مطل جدايل'],
                    ['en' => 'Saint John Area', 'ar' => 'منطقة مار يوحنا'],
                ],
            ],
            [
                'en' => 'Batroun',
                'ar' => 'البترون',
                'areas' => [
                    ['en' => 'Batroun City Center', 'ar' => 'وسط البترون'],
                    ['en' => 'Kfar Abida', 'ar' => 'كفرعبيدا'],
                    ['en' => 'Heri', 'ar' => 'الهري'],
                    ['en' => 'Ijdabra', 'ar' => 'إجدبرا'],
                    ['en' => 'Douma', 'ar' => 'دوما'],
                    ['en' => 'Tannourine', 'ar' => 'تنورين'],
                    ['en' => 'Smar Jbeil', 'ar' => 'سمراء جبيل'],
                    ['en' => 'Bchaaleh', 'ar' => 'بشعلة'],
                    ['en' => 'Ras Nahash', 'ar' => 'رأس نحاش'],
                    ['en' => 'Batroun Seaside', 'ar' => 'شاطئ البترون'],
                    ['en' => 'Kfour El Arbi', 'ar' => 'كفور العرب'],
                    ['en' => 'Thoum', 'ar' => 'الثّوم'],
                    ['en' => 'Hamat', 'ar' => 'حامات'],
                    ['en' => 'Beit Chlala', 'ar' => 'بيت شلالا'],
                    ['en' => 'Mrah Chdid', 'ar' => 'مراح شديد'],
                    ['en' => 'Chekka Border', 'ar' => 'حدود شكا'],
                    ['en' => 'Kfifan', 'ar' => 'كفيفان'],
                    ['en' => 'Ouadi Qanoubine', 'ar' => 'وادي قنوبين'],
                    ['en' => 'Batroun Old Souk', 'ar' => 'السوق القديم'],
                    ['en' => 'Ain Kfaa', 'ar' => 'عين كفا'],
                    ['en' => 'Batroun Vineyards Area', 'ar' => 'منطقة الكروم'],
                    ['en' => 'Mar Elias', 'ar' => 'مار الياس'],
                    ['en' => 'Mrah El Jabal', 'ar' => 'مراح الجبل'],
                    ['en' => 'Tallet Batroun', 'ar' => 'تلة البترون'],
                    ['en' => 'Ijdabra Heights', 'ar' => 'علية إجدبرا'],
                    ['en' => 'Ghabat Batroun', 'ar' => 'غابات البترون'],
                    ['en' => 'Saint Rafka', 'ar' => 'مار رفقا'],
                    ['en' => 'Ras Chekka Border', 'ar' => 'حدود رأس شكا'],
                    ['en' => 'Deir Mar Youhanna', 'ar' => 'دير مار يوحنا'],
                    ['en' => 'Old Port', 'ar' => 'المرفأ القديم'],
                ],
            ],
            [
                'en' => 'Danniyeh (Syr Dinniyeh)',
                'ar' => 'الضنية',
                'areas' => [
                    ['en' => 'Syr Dinniyeh', 'ar' => 'سير الضنية'],
                    ['en' => 'Ain Qadib', 'ar' => 'عين قادب'],
                    ['en' => 'Bakhoun', 'ar' => 'بخعون'],
                    ['en' => 'Sir', 'ar' => 'سير'],
                    ['en' => 'Aassoun', 'ar' => 'عاصون'],
                    ['en' => 'Bqaa Sifrin', 'ar' => 'بقاع صفرين'],
                    ['en' => 'Sfireh', 'ar' => 'سفيرة'],
                    ['en' => 'Kefr Hata', 'ar' => 'كفر حاتا'],
                    ['en' => 'Beit El Faqs', 'ar' => 'بيت الفقس'],
                    ['en' => 'Bqaaatash', 'ar' => 'بقعتاش'],
                    ['en' => 'Bazbina', 'ar' => 'بزبينا'],
                    ['en' => 'Kfarbnin', 'ar' => 'كفر بنين'],
                    ['en' => 'Karnayel', 'ar' => 'قرنايل'],
                    ['en' => 'Qarsaita', 'ar' => 'قرصيتا'],
                    ['en' => 'Kfar Habou', 'ar' => 'كفر حبو'],
                    ['en' => 'Bakhoun Heights', 'ar' => 'علية بخعون'],
                    ['en' => 'Syr Old Road', 'ar' => 'الطريق القديمة - سير'],
                    ['en' => 'Dinniyeh Hills', 'ar' => 'تلال الضنية'],
                    ['en' => 'Mazraat Aassoun', 'ar' => 'مزرعة عاصون'],
                    ['en' => 'Arbet Qozhaya', 'ar' => 'عربة قزحيا'],
                    ['en' => 'Kfarbnin Valley', 'ar' => 'وادي كفر بنين'],
                    ['en' => 'Sfireh Upper', 'ar' => 'سفيرة العليا'],
                    ['en' => 'Sir Market', 'ar' => 'سوق سير'],
                    ['en' => 'Sir Medical Zone', 'ar' => 'منطقة سير الطبية'],
                    ['en' => 'Aassoun Riverbank', 'ar' => 'ضفاف نهر عاصون'],
                    ['en' => 'Sir School District', 'ar' => 'منطقة مدارس سير'],
                    ['en' => 'Beit El Faqs Border', 'ar' => 'حدود بيت الفقس'],
                    ['en' => 'Syr Forest Edge', 'ar' => 'أطراف غابة سير'],
                    ['en' => 'Qarsaita View', 'ar' => 'مطل قرصيتا'],
                    ['en' => 'Ain Aqrine', 'ar' => 'عين أقرين'],
                ],
            ],
            [
                'en' => 'Minieh',
                'ar' => 'المنية',
                'areas' => [
                    ['en' => 'Minieh Center', 'ar' => 'وسط المنية'],
                    ['en' => 'Minieh Hospital Area', 'ar' => 'منطقة مستشفى المنية'],
                    ['en' => 'Minieh Schools Zone', 'ar' => 'منطقة مدارس المنية'],
                    ['en' => 'Qalamoun Border', 'ar' => 'حدود القلمون'],
                    ['en' => 'Minieh Agricultural Land', 'ar' => 'أراضي زراعية - المنية'],
                    ['en' => 'Wata Minieh', 'ar' => 'وطى المنية'],
                    ['en' => 'Bohsas Border', 'ar' => 'حدود البحصاص'],
                    ['en' => 'Ain El Mouh', 'ar' => 'عين الموح'],
                    ['en' => 'Jameh Area', 'ar' => 'منطقة الجامع'],
                    ['en' => 'Kfarsaroun Border', 'ar' => 'حدود كفرصارون'],
                    ['en' => 'Ain El Gharbiyeh', 'ar' => 'العين الغربية'],
                    ['en' => 'Al Dahiyeh', 'ar' => 'الضاحية'],
                    ['en' => 'Minieh Corniche', 'ar' => 'كورنيش المنية'],
                    ['en' => 'El Hamam Street', 'ar' => 'شارع الحمام'],
                    ['en' => 'Talet El Minieh', 'ar' => 'تلة المنية'],
                    ['en' => 'Siyaha Area', 'ar' => 'منطقة السياحة'],
                    ['en' => 'Mazraat Minieh', 'ar' => 'مزرعة المنية'],
                    ['en' => 'Nahr El Bared Edge', 'ar' => 'طرف نهر البارد'],
                    ['en' => 'Coastal Minieh', 'ar' => 'المنية الساحلية'],
                    ['en' => 'Harba Zone', 'ar' => 'منطقة حربا'],
                    ['en' => 'Tallet Siyaha', 'ar' => 'تلة السياحة'],
                    ['en' => 'Minieh North Road', 'ar' => 'الطريق الشمالي'],
                    ['en' => 'Hay El Salam', 'ar' => 'حي السلام'],
                    ['en' => 'Mar Elias Area', 'ar' => 'منطقة مار الياس'],
                    ['en' => 'Qobbeh Border', 'ar' => 'حدود القبة'],
                    ['en' => 'Fanar Minieh', 'ar' => 'فنار المنية'],
                    ['en' => 'Ain El Sihha', 'ar' => 'عين الصحة'],
                    ['en' => 'Minieh Old Souk', 'ar' => 'السوق القديم'],
                    ['en' => 'Airport Road Edge', 'ar' => 'طرف طريق المطار'],
                    ['en' => 'Ain Al Dahab', 'ar' => 'عين الذهب'],
                ],
            ],
            [
                'en' => 'Halba',
                'ar' => 'حلبا',
                'areas' => [
                    ['en' => 'Halba Center', 'ar' => 'وسط حلبا'],
                    ['en' => 'Halba Municipality Zone', 'ar' => 'منطقة البلدية'],
                    ['en' => 'Old Halba Souk', 'ar' => 'سوق حلبا القديم'],
                    ['en' => 'Halba Corniche', 'ar' => 'كورنيش حلبا'],
                    ['en' => 'Wata Halba', 'ar' => 'وطى حلبا'],
                    ['en' => 'Mar Touma', 'ar' => 'مار توما'],
                    ['en' => 'Ain Halba', 'ar' => 'عين حلبا'],
                    ['en' => 'Mar Elias', 'ar' => 'مار الياس'],
                    ['en' => 'Beit Halba', 'ar' => 'بيت حلبا'],
                    ['en' => 'Qantara', 'ar' => 'القنطرة'],
                    ['en' => 'Halba Schools Area', 'ar' => 'منطقة المدارس'],
                    ['en' => 'Halba Hospital Zone', 'ar' => 'منطقة المستشفى'],
                    ['en' => 'Minyara Border', 'ar' => 'حدود منيارة'],
                    ['en' => 'Bazbina Border', 'ar' => 'حدود بزبينا'],
                    ['en' => 'Ain Al Joz', 'ar' => 'عين الجوز'],
                    ['en' => 'Saint Doumit', 'ar' => 'مار دوميط'],
                    ['en' => 'Halba Industrial Zone', 'ar' => 'المنطقة الصناعية'],
                    ['en' => 'Qamouh', 'ar' => 'القاموع'],
                    ['en' => 'Halba Farmland', 'ar' => 'أراضي زراعية'],
                    ['en' => 'Church District', 'ar' => 'حي الكنيسة'],
                    ['en' => 'Halba Souk Extension', 'ar' => 'امتداد السوق'],
                    ['en' => 'Abou Halba', 'ar' => 'أبو حلبا'],
                    ['en' => 'Mazraat Halba', 'ar' => 'مزرعة حلبا'],
                    ['en' => 'Kroum Halba', 'ar' => 'كروم حلبا'],
                    ['en' => 'Halba Upper Hills', 'ar' => 'علية حلبا'],
                    ['en' => 'Zouk Halba', 'ar' => 'زوق حلبا'],
                    ['en' => 'Ain Al Saydeh', 'ar' => 'عين السيدة'],
                    ['en' => 'Jisr Halba', 'ar' => 'جسر حلبا'],
                    ['en' => 'Halba East Road', 'ar' => 'الطريق الشرقي'],
                    ['en' => 'Hay El Nour', 'ar' => 'حي النور'],
                ],
            ],
            [
                'en' => 'Bebnine',
                'ar' => 'ببنين',
                'areas' => [
                    ['en' => 'Bebnine Center', 'ar' => 'وسط ببنين'],
                    ['en' => 'Qabr Chamoun Border', 'ar' => 'حدود قبر شمون'],
                    ['en' => 'Jabal Bebnine', 'ar' => 'جبل ببنين'],
                    ['en' => 'Ain Bebnine', 'ar' => 'عين ببنين'],
                    ['en' => 'Hay El Saydeh', 'ar' => 'حي السيدة'],
                    ['en' => 'Kroum Bebnine', 'ar' => 'كروم ببنين'],
                    ['en' => 'Wadi El Bebnine', 'ar' => 'وادي ببنين'],
                    ['en' => 'Souk Bebnine', 'ar' => 'سوق ببنين'],
                    ['en' => 'Mazraat Bebnine', 'ar' => 'مزرعة ببنين'],
                    ['en' => 'Fanar Bebnine', 'ar' => 'فنار ببنين'],
                    ['en' => 'Beit Al Bebnine', 'ar' => 'بيت الببنين'],
                    ['en' => 'Hay El Nour', 'ar' => 'حي النور'],
                    ['en' => 'Bebnine Church District', 'ar' => 'حي الكنيسة'],
                    ['en' => 'Bebnine School Area', 'ar' => 'منطقة المدارس'],
                    ['en' => 'South Bebnine Road', 'ar' => 'طريق الجنوب'],
                    ['en' => 'Bebnine River Bank', 'ar' => 'ضفاف النهر'],
                    ['en' => 'Upper Bebnine', 'ar' => 'ببنين العليا'],
                    ['en' => 'Lower Bebnine', 'ar' => 'ببنين السفلى'],
                    ['en' => 'Ain El Saydeh', 'ar' => 'عين السيدة'],
                    ['en' => 'Al Rihaniyeh', 'ar' => 'الريحانية'],
                    ['en' => 'Jisr Bebnine', 'ar' => 'جسر ببنين'],
                    ['en' => 'Dar Bebnine', 'ar' => 'دار ببنين'],
                    ['en' => 'Hay El Gharbi', 'ar' => 'الحي الغربي'],
                    ['en' => 'Hay El Sharqi', 'ar' => 'الحي الشرقي'],
                    ['en' => 'Corniche Bebnine', 'ar' => 'كورنيش ببنين'],
                    ['en' => 'Bayader Bebnine', 'ar' => 'بيادر ببنين'],
                    ['en' => 'Ain El Kharroubeh', 'ar' => 'عين الخرّوبة'],
                    ['en' => 'Bebnine Hillside', 'ar' => 'منحدر ببنين'],
                    ['en' => 'Zahrani Border', 'ar' => 'حدود الزهراني'],
                    ['en' => 'Bebnine Municipal Stadium', 'ar' => 'ملعب البلدية'],
                ],
            ],
            [
                'en' => 'Sidon (Saida)',
                'ar' => 'صيدا',
                'areas' => [
                    ['en' => 'Old Souk', 'ar' => 'السوق القديم'],
                    ['en' => 'Saida Castle', 'ar' => 'قلعة صيدا'],
                    ['en' => 'Aabra', 'ar' => 'عبرا'],
                    ['en' => 'Rmeileh Border', 'ar' => 'حدود رميلة'],
                    ['en' => 'East Boulevard', 'ar' => 'بولفار الشرق'],
                    ['en' => 'Coastal Corniche', 'ar' => 'الكورنيش البحري'],
                    ['en' => 'Saida Port Area', 'ar' => 'منطقة المرفأ'],
                    ['en' => 'Majdalyoun', 'ar' => 'مجدليون'],
                    ['en' => 'Kfarjarra', 'ar' => 'كفرجرة'],
                    ['en' => 'Haret Saida', 'ar' => 'حارة صيدا'],
                    ['en' => 'Darb El Sim', 'ar' => 'درب السيم'],
                    ['en' => 'Saydeh Church Area', 'ar' => 'منطقة كنيسة السيدة'],
                    ['en' => 'Ain El Helweh Camp', 'ar' => 'مخيم عين الحلوة'],
                    ['en' => 'Mieh Mieh', 'ar' => 'مية ومية'],
                    ['en' => 'Saida Western Entrance', 'ar' => 'مدخل صيدا الغربي'],
                    ['en' => 'Jisr El Zahrani', 'ar' => 'جسر الزهراني'],
                    ['en' => 'Saida Mall District', 'ar' => 'منطقة مول صيدا'],
                    ['en' => 'Kfar Falous', 'ar' => 'كفر فالوس'],
                    ['en' => 'Hay El Rahma', 'ar' => 'حي الرحمة'],
                    ['en' => 'Industrial Zone', 'ar' => 'المنطقة الصناعية'],
                    ['en' => 'Choueifat Border', 'ar' => 'حدود الشويفات'],
                    ['en' => 'New Saida', 'ar' => 'صيدا الجديدة'],
                    ['en' => 'Zahrani Edge', 'ar' => 'طرف الزهراني'],
                    ['en' => 'Hay El Shariah', 'ar' => 'حي الشريعة'],
                    ['en' => 'Jabal El Hssen', 'ar' => 'جبل الحسن'],
                    ['en' => 'Qraiyeh', 'ar' => 'القريعة'],
                    ['en' => 'Mazraat Saida', 'ar' => 'مزرعة صيدا'],
                    ['en' => 'Bqosta', 'ar' => 'بقسطا'],
                    ['en' => 'El Qalaa', 'ar' => 'القلعة'],
                    ['en' => 'Hay El Wasta', 'ar' => 'حي الوسطى'],
                ],
            ],

            [
                'en' => 'Tyre (Sour)',
                'ar' => 'صور',
                'areas' => [
                    ['en' => 'Old Tyre', 'ar' => 'صور القديمة'],
                    ['en' => 'Tyre Port', 'ar' => 'ميناء صور'],
                    ['en' => 'Tyre Sea Road', 'ar' => 'طريق البحر'],
                    ['en' => 'Ain Baal Road', 'ar' => 'طريق عين بعال'],
                    ['en' => 'Qasmieh', 'ar' => 'القاسمية'],
                    ['en' => 'Borj El Shimali', 'ar' => 'برج الشمالي'],
                    ['en' => 'Rashidieh Camp', 'ar' => 'مخيم الرشيدية'],
                    ['en' => 'Maashouk', 'ar' => 'المعشوق'],
                    ['en' => 'Jal Al Baher', 'ar' => 'جال البحر'],
                    ['en' => 'Abbassieh', 'ar' => 'العباسية'],
                    ['en' => 'Bazouriyeh', 'ar' => 'البازورية'],
                    ['en' => 'Hanaway', 'ar' => 'حنوية'],
                    ['en' => 'Tyre Market', 'ar' => 'سوق صور'],
                    ['en' => 'Roman Ruins', 'ar' => 'الآثار الرومانية'],
                    ['en' => 'Wata Tyre', 'ar' => 'وطى صور'],
                    ['en' => 'Chamaa', 'ar' => 'شمع'],
                    ['en' => 'Qlayleh', 'ar' => 'القليلة'],
                    ['en' => 'Burj Rahhal', 'ar' => 'برج رحال'],
                    ['en' => 'Tyre Corniche', 'ar' => 'كورنيش صور'],
                    ['en' => 'Tyre Stadium Area', 'ar' => 'منطقة الملعب'],
                    ['en' => 'Tyre Industrial Zone', 'ar' => 'المنطقة الصناعية'],
                    ['en' => 'Hay El Jawameh', 'ar' => 'حي الجوامع'],
                    ['en' => 'Hay El Jamhourieh', 'ar' => 'حي الجمهورية'],
                    ['en' => 'Tyre Marina', 'ar' => 'مرسى صور'],
                    ['en' => 'Khirbet Silm', 'ar' => 'خربة سلم'],
                    ['en' => 'Tyre University District', 'ar' => 'منطقة الجامعة'],
                    ['en' => 'Al Hosh', 'ar' => 'الحوش'],
                    ['en' => 'Deir Qanoun Ras El Ain', 'ar' => 'دير قانون رأس العين'],
                    ['en' => 'Naqoura Border', 'ar' => 'حدود الناقورة'],
                    ['en' => 'Zahrani Border', 'ar' => 'حدود الزهراني'],
                ],
            ],
            [
                'en' => 'Jezzine',
                'ar' => 'جزين',
                'areas' => [
                    ['en' => 'Jezzine Center', 'ar' => 'وسط جزين'],
                    ['en' => 'Jezzine Waterfall Area', 'ar' => 'منطقة الشلال'],
                    ['en' => 'Ain Majdalain', 'ar' => 'عين مجدلين'],
                    ['en' => 'Kfarhouna', 'ar' => 'كفرحونة'],
                    ['en' => 'Roum', 'ar' => 'روم'],
                    ['en' => 'Maknouniyeh', 'ar' => 'مكنونية'],
                    ['en' => 'Bkassine', 'ar' => 'بكاسين'],
                    ['en' => 'Ain Zhalta', 'ar' => 'عين زحلتا'],
                    ['en' => 'Sabah', 'ar' => 'صباح'],
                    ['en' => 'Ain El Delb', 'ar' => 'عين الدلب'],
                    ['en' => 'Hay El Saydeh', 'ar' => 'حي السيدة'],
                    ['en' => 'Dahr El Ahmar', 'ar' => 'ضهر الأحمر'],
                    ['en' => 'Saydet El Talleh', 'ar' => 'سيدة التلة'],
                    ['en' => 'Ain El Mir', 'ar' => 'عين المير'],
                    ['en' => 'Zoghdraiya', 'ar' => 'زغدرايا'],
                    ['en' => 'Mazraat El Saydeh', 'ar' => 'مزرعة السيدة'],
                    ['en' => 'Kfar Falous Border', 'ar' => 'حدود كفر فالوس'],
                    ['en' => 'Qaitouli', 'ar' => 'قيتولي'],
                    ['en' => 'Bouslaiya', 'ar' => 'بوسلاية'],
                    ['en' => 'Jezzine Schools Area', 'ar' => 'منطقة المدارس'],
                    ['en' => 'Mar Gerges', 'ar' => 'مار جرجس'],
                    ['en' => 'Mazraat Jezzine', 'ar' => 'مزرعة جزين'],
                    ['en' => 'Chouf Border', 'ar' => 'حدود الشوف'],
                    ['en' => 'Kfar Melki', 'ar' => 'كفرملكي'],
                    ['en' => 'El Rihaniyeh', 'ar' => 'الريحانية'],
                    ['en' => 'Jarmaq', 'ar' => 'جرمق'],
                    ['en' => 'Saint Joseph District', 'ar' => 'منطقة مار يوسف'],
                    ['en' => 'Jezzine Forest Entrance', 'ar' => 'مدخل غابة جزين'],
                    ['en' => 'Nabeh El Safa', 'ar' => 'نبع الصفا'],
                    ['en' => 'Jezzine Corniche', 'ar' => 'كورنيش جزين'],
                ],
            ],
            [
                'en' => 'Sarafand',
                'ar' => 'الصرفند',
                'areas' => [
                    ['en' => 'Sarafand Center', 'ar' => 'وسط الصرفند'],
                    ['en' => 'Kharroub', 'ar' => 'الخرّوب'],
                    ['en' => 'Sarafand Seaside', 'ar' => 'الصرفند البحرية'],
                    ['en' => 'Mazraat Sarafand', 'ar' => 'مزرعة الصرفند'],
                    ['en' => 'Hay El Fawqa', 'ar' => 'الحي الفوقا'],
                    ['en' => 'Wata Sarafand', 'ar' => 'وطى الصرفند'],
                    ['en' => 'Sarafand Market', 'ar' => 'سوق الصرفند'],
                    ['en' => 'Zahrani Road', 'ar' => 'طريق الزهراني'],
                    ['en' => 'Ain El Sarafand', 'ar' => 'عين الصرفند'],
                    ['en' => 'Kfar Dounine Border', 'ar' => 'حدود كفر دونين'],
                    ['en' => 'Saydet El Sarafand', 'ar' => 'سيدة الصرفند'],
                    ['en' => 'Abou El Aswad Border', 'ar' => 'حدود أبو الأسود'],
                    ['en' => 'Industrial Zone', 'ar' => 'المنطقة الصناعية'],
                    ['en' => 'Mar Elias District', 'ar' => 'حي مار الياس'],
                    ['en' => 'Sarafand Municipality', 'ar' => 'بلدية الصرفند'],
                    ['en' => 'Tallet Sarafand', 'ar' => 'تلة الصرفند'],
                    ['en' => 'Sarafand Fishing Port', 'ar' => 'ميناء الصيد'],
                    ['en' => 'Bayader Sarafand', 'ar' => 'بيادر الصرفند'],
                    ['en' => 'Ain El Shaab', 'ar' => 'عين الشعب'],
                    ['en' => 'Qalaat El Sarafand', 'ar' => 'قلعة الصرفند'],
                    ['en' => 'Sarafand River Side', 'ar' => 'ضفاف نهر الصرفند'],
                    ['en' => 'Khallet El Warde', 'ar' => 'خلة الوردة'],
                    ['en' => 'Rihaniyeh View', 'ar' => 'مطل الريحانية'],
                    ['en' => 'Sarafand Cemetery Zone', 'ar' => 'منطقة المقبرة'],
                    ['en' => 'Hay El Sheikh', 'ar' => 'حي الشيخ'],
                    ['en' => 'Hay El Midan', 'ar' => 'حي الميدان'],
                    ['en' => 'El Maslakh', 'ar' => 'المسلخ'],
                    ['en' => 'Souk El Sabe', 'ar' => 'سوق السبع'],
                    ['en' => 'Kroum El Ain', 'ar' => 'كروم العين'],
                    ['en' => 'Sarafand Entrance', 'ar' => 'مدخل الصرفند'],
                ],
            ],
            [
                'en' => 'Nabatieh',
                'ar' => 'النبطية',
                'areas' => [
                    ['en' => 'Nabatieh El Tahta', 'ar' => 'النبطية التحتا'],
                    ['en' => 'Nabatieh El Fawqa', 'ar' => 'النبطية الفوقا'],
                    ['en' => 'Hay El Serail', 'ar' => 'حي السراي'],
                    ['en' => 'Ain Qana Road', 'ar' => 'طريق عين قانا'],
                    ['en' => 'Nabatieh Souk', 'ar' => 'سوق النبطية'],
                    ['en' => 'Kfar Dounine Border', 'ar' => 'حدود كفر دونين'],
                    ['en' => 'Marjeyoun Road', 'ar' => 'طريق مرجعيون'],
                    ['en' => 'Zebdine Border', 'ar' => 'حدود زبدين'],
                    ['en' => 'Jamaa Area', 'ar' => 'منطقة الجامع'],
                    ['en' => 'Wata Nabatieh', 'ar' => 'وطى النبطية'],
                    ['en' => 'Old Cemetery Zone', 'ar' => 'منطقة المقبرة القديمة'],
                    ['en' => 'Al Charkiyeh', 'ar' => 'الشرقية'],
                    ['en' => 'Nabatieh University District', 'ar' => 'منطقة الجامعة'],
                    ['en' => 'Ain El Medfoun', 'ar' => 'عين المدفون'],
                    ['en' => 'Saydeh District', 'ar' => 'حي السيدة'],
                    ['en' => 'Nabatieh Sports City', 'ar' => 'المدينة الرياضية'],
                    ['en' => 'Industrial Zone', 'ar' => 'المنطقة الصناعية'],
                    ['en' => 'Kfar Remmane', 'ar' => 'كفررمان'],
                    ['en' => 'Mazraat Nabatieh', 'ar' => 'مزرعة النبطية'],
                    ['en' => 'Hay El Hoss', 'ar' => 'حي الحص'],
                    ['en' => 'Al Toufaht', 'ar' => 'التفاح'],
                    ['en' => 'Kfar Jouz', 'ar' => 'كفرجوز'],
                    ['en' => 'Shqif Fortress', 'ar' => 'قلعة الشقيف'],
                    ['en' => 'Mar Elias', 'ar' => 'مار الياس'],
                    ['en' => 'Ain El Tineh', 'ar' => 'عين التينة'],
                    ['en' => 'Tallet Nabatieh', 'ar' => 'تلة النبطية'],
                    ['en' => 'Kroum Nabatieh', 'ar' => 'كروم النبطية'],
                    ['en' => 'Souk Al Khan', 'ar' => 'سوق الخان'],
                    ['en' => 'Nabatieh Entrance', 'ar' => 'مدخل النبطية'],
                    ['en' => 'El Maslakh', 'ar' => 'المسلخ'],
                ],
            ],
            [
                'en' => 'Bint Jbeil',
                'ar' => 'بنت جبيل',
                'areas' => [
                    ['en' => 'Bint Jbeil Center', 'ar' => 'وسط بنت جبيل'],
                    ['en' => 'Maroun El Ras Border', 'ar' => 'حدود مارون الراس'],
                    ['en' => 'Ainata Border', 'ar' => 'حدود عيناتا'],
                    ['en' => 'Sahl Bint Jbeil', 'ar' => 'سهل بنت جبيل'],
                    ['en' => 'Kharroubeh', 'ar' => 'الخرّوبة'],
                    ['en' => 'Kroum Jbeil', 'ar' => 'كروم جبيل'],
                    ['en' => 'Hay El Midan', 'ar' => 'حي الميدان'],
                    ['en' => 'Bint Jbeil Stadium', 'ar' => 'ملعب بنت جبيل'],
                    ['en' => 'Hay El Rihaniyeh', 'ar' => 'حي الريحانية'],
                    ['en' => 'Ain El Joz', 'ar' => 'عين الجوز'],
                    ['en' => 'Tallet Bint Jbeil', 'ar' => 'تلة بنت جبيل'],
                    ['en' => 'Souk Bint Jbeil', 'ar' => 'سوق بنت جبيل'],
                    ['en' => 'Hay El Saydeh', 'ar' => 'حي السيدة'],
                    ['en' => 'Mazraat Bint Jbeil', 'ar' => 'مزرعة بنت جبيل'],
                    ['en' => 'Jal El Bahr Border', 'ar' => 'حدود جال البحر'],
                    ['en' => 'Wata Bint Jbeil', 'ar' => 'وطى بنت جبيل'],
                    ['en' => 'Qalaa El Sheikh', 'ar' => 'قلعة الشيخ'],
                    ['en' => 'Hay El Imam', 'ar' => 'حي الإمام'],
                    ['en' => 'Saint Elias', 'ar' => 'مار الياس'],
                    ['en' => 'Industrial Road', 'ar' => 'طريق الصناعية'],
                    ['en' => 'Jisr El Bint', 'ar' => 'جسر البنت'],
                    ['en' => 'Tallet Zahrani', 'ar' => 'تلة الزهراني'],
                    ['en' => 'Kroum El Kharroubeh', 'ar' => 'كروم الخرّوبة'],
                    ['en' => 'Mashroua Bint Jbeil', 'ar' => 'مشروع بنت جبيل'],
                    ['en' => 'Ain El Saydeh', 'ar' => 'عين السيدة'],
                    ['en' => 'Zahrani Edge', 'ar' => 'طرف الزهراني'],
                    ['en' => 'Bayader El Souk', 'ar' => 'بيادر السوق'],
                    ['en' => 'Ras Bint Jbeil', 'ar' => 'رأس بنت جبيل'],
                    ['en' => 'Shqif Bint Jbeil', 'ar' => 'شقيف بنت جبيل'],
                    ['en' => 'Hay El Sheikh', 'ar' => 'حي الشيخ'],
                ],
            ],
            [
                'en' => 'Marjayoun',
                'ar' => 'مرجعيون',
                'areas' => [
                    ['en' => 'Marjayoun Center', 'ar' => 'وسط مرجعيون'],
                    ['en' => 'Qlayaa', 'ar' => 'القليعة'],
                    ['en' => 'Burj El Moulouk', 'ar' => 'برج الملوك'],
                    ['en' => 'Khiam', 'ar' => 'الخيام'],
                    ['en' => 'Debbine', 'ar' => 'دبين'],
                    ['en' => 'El Marj', 'ar' => 'المرج'],
                    ['en' => 'Mazraat Marjayoun', 'ar' => 'مزرعة مرجعيون'],
                    ['en' => 'Qantara', 'ar' => 'القنطرة'],
                    ['en' => 'Wazzani', 'ar' => 'الوزاني'],
                    ['en' => 'Deir Mimas', 'ar' => 'دير ميماس'],
                    ['en' => 'Kfar Kila Border', 'ar' => 'حدود كفركلا'],
                    ['en' => 'Ain Arab', 'ar' => 'عين عرب'],
                    ['en' => 'Markaba', 'ar' => 'مركبا'],
                    ['en' => 'Tallet Khiam', 'ar' => 'تلة الخيام'],
                    ['en' => 'Ain El Tineh', 'ar' => 'عين التينة'],
                    ['en' => 'Mar Elias', 'ar' => 'مار الياس'],
                    ['en' => 'Jdeidet Marjayoun', 'ar' => 'جديدة مرجعيون'],
                    ['en' => 'Industrial Zone', 'ar' => 'المنطقة الصناعية'],
                    ['en' => 'Hay El Jamiyeh', 'ar' => 'حي الجامعية'],
                    ['en' => 'Mar Gerges', 'ar' => 'مار جرجس'],
                    ['en' => 'Hay El Saydeh', 'ar' => 'حي السيدة'],
                    ['en' => 'Jisr Marjayoun', 'ar' => 'جسر مرجعيون'],
                    ['en' => 'Bayader Marjayoun', 'ar' => 'بيادر مرجعيون'],
                    ['en' => 'Ras Marjayoun', 'ar' => 'رأس مرجعيون'],
                    ['en' => 'Tallet Zahrani', 'ar' => 'تلة الزهراني'],
                    ['en' => 'Hay El Imam', 'ar' => 'حي الإمام'],
                    ['en' => 'Old Souk', 'ar' => 'السوق القديم'],
                    ['en' => 'Marjayoun Border Zone', 'ar' => 'منطقة الحدود'],
                    ['en' => 'Ain Ebel Border', 'ar' => 'حدود عين إبل'],
                    ['en' => 'Wata Marjayoun', 'ar' => 'وطى مرجعيون'],
                ],
            ],
            [
                'en' => 'Hasbaya',
                'ar' => 'حاصبيا',
                'areas' => [
                    ['en' => 'Hasbaya Center', 'ar' => 'وسط حاصبيا'],
                    ['en' => 'Kawkaba', 'ar' => 'كوكبا'],
                    ['en' => 'Ain Qinia', 'ar' => 'عين قنيا'],
                    ['en' => 'Kfar Hamam', 'ar' => 'كفر حمام'],
                    ['en' => 'Kfeir', 'ar' => 'كفير'],
                    ['en' => 'Helta', 'ar' => 'هلتا'],
                    ['en' => 'Ain Jarfa', 'ar' => 'عين جرفا'],
                    ['en' => 'Mimes', 'ar' => 'ميمس'],
                    ['en' => 'Debbine', 'ar' => 'دبين'],
                    ['en' => 'Khirbet Rouha', 'ar' => 'خربة روحا'],
                    ['en' => 'Ain Tinta', 'ar' => 'عين تنتا'],
                    ['en' => 'Al Mari', 'ar' => 'الماري'],
                    ['en' => 'Hasrout', 'ar' => 'حاصروت'],
                    ['en' => 'Chwayya', 'ar' => 'شويا'],
                    ['en' => 'Rachaya El Foukhar', 'ar' => 'راشيا الفخار'],
                    ['en' => 'El Meri', 'ar' => 'الماري'],
                    ['en' => 'Kawkaba El Fawka', 'ar' => 'كوكبا الفوقا'],
                ],
            ],
            [
                'en' => 'Kfar Kila',
                'ar' => 'كفركلا',
                'areas' => [
                    ['en' => 'Kfar Kila Center', 'ar' => 'وسط كفركلا'],
                    ['en' => 'Boustan El Arab', 'ar' => 'بستان العرب'],
                    ['en' => 'Ras El Bayader', 'ar' => 'رأس البيادر'],
                    ['en' => 'Marj El Zouhour', 'ar' => 'مرج الزهور'],
                    ['en' => 'Wadi Kfar Kila', 'ar' => 'وادي كفركلا'],
                    ['en' => 'Hay El Jabal', 'ar' => 'حي الجبل'],
                    ['en' => 'Hay El Midan', 'ar' => 'حي الميدان'],
                    ['en' => 'Talet Al Khirbeh', 'ar' => 'تلة الخربة'],
                    ['en' => 'Mazraet Kfar Kila', 'ar' => 'مزرعة كفركلا'],
                    ['en' => 'Shallaliyeh', 'ar' => 'شلالية'],
                    ['en' => 'Dahr El Mokhtar', 'ar' => 'ضهر المختار'],
                ],
            ],
            [
                'en' => 'Zahle',
                'ar' => 'زحلة',
                'areas' => [
                    ['en' => 'Haouch El Omara', 'ar' => 'حوش الأمراء'],
                    ['en' => 'Ksara', 'ar' => 'كسارة'],
                    ['en' => 'Wadi El Arayesh', 'ar' => 'وادي العرايش'],
                    ['en' => 'Zahle Center', 'ar' => 'وسط زحلة'],
                    ['en' => 'Ain El Hajal', 'ar' => 'عين الحجل'],
                    ['en' => 'Ain El Ghossein', 'ar' => 'عين الغصين'],
                    ['en' => 'Hay El Midan', 'ar' => 'حي الميدان'],
                    ['en' => 'Maallaqa', 'ar' => 'المعلّقة'],
                    ['en' => 'Houch Hala', 'ar' => 'حوش حالا'],
                    ['en' => 'Ksara Hills', 'ar' => 'تلال كسارة'],
                    ['en' => 'Sayyidat Zahle', 'ar' => 'سيدة زحلة'],
                    ['en' => 'Qab Elias Road', 'ar' => 'طريق قب الياس'],
                    ['en' => 'Mouallaka Hills', 'ar' => 'تلال المعلقة'],
                    ['en' => 'Industrial City', 'ar' => 'المنطقة الصناعية'],
                    ['en' => 'Ain Traz', 'ar' => 'عين طرَاز'],
                    ['en' => 'Tallet Zahle', 'ar' => 'تلة زحلة'],
                ],
            ],
            [
                'en' => 'Riyaq',
                'ar' => 'رياق',
                'areas' => [
                    ['en' => 'Riyaq Center', 'ar' => 'وسط رياق'],
                    ['en' => 'Riyaq West', 'ar' => 'رياق الغربية'],
                    ['en' => 'Riyaq Airport', 'ar' => 'مطار رياق'],
                    ['en' => 'Hay El Matar', 'ar' => 'حي المطار'],
                    ['en' => 'Al Mustashfa', 'ar' => 'المستشفى'],
                    ['en' => 'Mazraat Riyaq', 'ar' => 'مزرعة رياق'],
                    ['en' => 'Tallet Riyaq', 'ar' => 'تلة رياق'],
                    ['en' => 'Mar Takla', 'ar' => 'مار تقلا'],
                    ['en' => 'Hay El Marj', 'ar' => 'حي المرج'],
                    ['en' => 'Wadi El Nahleh', 'ar' => 'وادي النحلة'],
                    ['en' => 'Riyaq Ain', 'ar' => 'عين رياق'],
                    ['en' => 'Sahat Riyaq', 'ar' => 'ساحة رياق'],
                    ['en' => 'El Midane', 'ar' => 'الميدان'],
                    ['en' => 'El Mahatta', 'ar' => 'المحطة'],
                    ['en' => 'Qasr Riyaq', 'ar' => 'قصر رياق'],
                ],
            ],
            [
                'en' => 'Chtaura',
                'ar' => 'شتورا',
                'areas' => [
                    ['en' => 'Chtaura Main Road', 'ar' => 'الطريق الرئيسي - شتورا'],
                    ['en' => 'Hay El Serail', 'ar' => 'حي السراي'],
                    ['en' => 'El Gharbi', 'ar' => 'الحي الغربي'],
                    ['en' => 'Hay El Jdid', 'ar' => 'حي الجديد'],
                    ['en' => 'Wadi El Delm', 'ar' => 'وادي الدلم'],
                    ['en' => 'Chtaura Heights', 'ar' => 'مرتفعات شتورا'],
                    ['en' => 'Tallet Chtaura', 'ar' => 'تلة شتورا'],
                    ['en' => 'Chtaura Souks', 'ar' => 'أسواق شتورا'],
                    ['en' => 'Ras Chtaura', 'ar' => 'رأس شتورا'],
                    ['en' => 'Old Chtaura', 'ar' => 'شتورا القديمة'],
                    ['en' => 'Industrial Area', 'ar' => 'المنطقة الصناعية'],
                    ['en' => 'Shmays', 'ar' => 'شميس'],
                    ['en' => 'El Marj Border', 'ar' => 'حدود المرج'],
                ],
            ],
            [
                'en' => 'Taanayel',
                'ar' => 'تعنايل',
                'areas' => [
                    ['en' => 'Taanayel Farms', 'ar' => 'مزارع تعنايل'],
                    ['en' => 'Taanayel Monastery', 'ar' => 'دير تعنايل'],
                    ['en' => 'Taanayel Plain', 'ar' => 'سهل تعنايل'],
                    ['en' => 'Taanayel East', 'ar' => 'تعنايل الشرقية'],
                    ['en' => 'Hay El Matar', 'ar' => 'حي المطار'],
                    ['en' => 'Tallet Taanayel', 'ar' => 'تلة تعنايل'],
                    ['en' => 'Wadi El Assi', 'ar' => 'وادي العاصي'],
                    ['en' => 'Old Taanayel', 'ar' => 'تعنايل القديمة'],
                    ['en' => 'Ain El Sitt', 'ar' => 'عين الست'],
                    ['en' => 'Beqaa Road', 'ar' => 'طريق البقاع'],
                    ['en' => 'Hay El Rassif', 'ar' => 'حي الرصيف'],
                ],
            ],
            [
                'en' => 'Qabb Elias',
                'ar' => 'قب الياس',
                'areas' => [
                    ['en' => 'Qabb Elias Main', 'ar' => 'قب الياس الرئيسي'],
                    ['en' => 'Qabb Elias Souks', 'ar' => 'أسواق قب الياس'],
                    ['en' => 'Mazraat Qabb Elias', 'ar' => 'مزرعة قب الياس'],
                    ['en' => 'Hay El Midan', 'ar' => 'حي الميدان'],
                    ['en' => 'Wadi Elias', 'ar' => 'وادي إلياس'],
                    ['en' => 'Qabb Elias Junction', 'ar' => 'مفترق قب الياس'],
                    ['en' => 'Hay El Ain', 'ar' => 'حي العين'],
                    ['en' => 'Hay El Mahatta', 'ar' => 'حي المحطة'],
                    ['en' => 'Khirbet Elias', 'ar' => 'خربة إلياس'],
                    ['en' => 'Zaroub Elias', 'ar' => 'زروب إلياس'],
                    ['en' => 'Industrial Area', 'ar' => 'المنطقة الصناعية'],
                    ['en' => 'Hay El Jdid', 'ar' => 'حي الجديد'],
                ],
            ],
            [
                'en' => 'Matn',
                'ar' => 'المتن',
                'areas' => [
                    ['en' => 'Jdeideh', 'ar' => 'جديدة المتن'],
                    ['en' => 'Bauchrieh', 'ar' => 'برج حمود'],
                    ['en' => 'Dekwaneh', 'ar' => 'الدكوانة'],
                    ['en' => 'Fanar', 'ar' => 'فنار'],
                    ['en' => 'Zalka', 'ar' => 'زلقا'],
                    ['en' => 'Antelias', 'ar' => 'انطلياس'],
                    ['en' => 'Dbayeh', 'ar' => 'ضبية'],
                    ['en' => 'Jal El Dib', 'ar' => 'جل الديب'],
                    ['en' => 'Mazraat Yachouh', 'ar' => 'مزرعة يشوع'],
                    ['en' => 'Roumieh', 'ar' => 'رومية'],
                    ['en' => 'Ain Saadeh', 'ar' => 'عين سعادة'],
                    ['en' => 'Ain Najm', 'ar' => 'عين نجم'],
                    ['en' => 'Bsalim', 'ar' => 'بصاليم'],
                    ['en' => 'Mezher', 'ar' => 'مزهر'],
                    ['en' => 'Beit Mery', 'ar' => 'بيت مري'],
                    ['en' => 'Brummana', 'ar' => 'برمانا'],
                    ['en' => 'Monte Verde', 'ar' => 'مونت فردي'],
                    ['en' => 'Rabweh', 'ar' => 'الرابوه'],
                    ['en' => 'Cornet Chehwan', 'ar' => 'قرنة شهوان'],
                    ['en' => 'Bayada', 'ar' => 'البياضة'],
                    ['en' => 'Mar Roukoz', 'ar' => 'مار روكز'],
                    ['en' => 'Bkennaya', 'ar' => 'بكفيا'],
                    ['en' => 'Aoukar', 'ar' => 'عوكر'],
                ],
            ],
            [
                'en' => 'Baalbek',
                'ar' => 'بعلبك',
                'areas' => [
                    ['en' => 'Baalbek Center', 'ar' => 'وسط بعلبك'],
                    ['en' => 'Ras El Ain', 'ar' => 'رأس العين'],
                    ['en' => 'Tal El Amara', 'ar' => 'تلّ الأمارة'],
                    ['en' => 'Hay El Serail', 'ar' => 'حي السراي'],
                    ['en' => 'Hay El Maslakh', 'ar' => 'حي المسلخ'],
                    ['en' => 'Mar Geryes', 'ar' => 'مار جرجس'],
                    ['en' => 'Wadi El Nahleh', 'ar' => 'وادي النحلة'],
                    ['en' => 'Basta Baalbek', 'ar' => 'بسطة بعلبك'],
                    ['en' => 'Baalbek Ruins Area', 'ar' => 'منطقة الآثار'],
                    ['en' => 'Douris', 'ar' => 'دورس'],
                    ['en' => 'Temnin El Fawqa', 'ar' => 'تمنين الفوقا'],
                    ['en' => 'Temnin El Tahta', 'ar' => 'تمنين التحتا'],
                    ['en' => 'Younine', 'ar' => 'يونين'],
                    ['en' => 'Iaat', 'ar' => 'إيعَات'],
                    ['en' => 'Nabi Chit', 'ar' => 'النبي شيت'],
                    ['en' => 'Jenta', 'ar' => 'جنطا'],
                    ['en' => 'Brital', 'ar' => 'بريتال'],
                    ['en' => 'Chmestar', 'ar' => 'شمستار'],
                ],
            ],
            [
                'en' => 'Hermel',
                'ar' => 'الهرمل',
                'areas' => [
                    ['en' => 'Hermel Center', 'ar' => 'وسط الهرمل'],
                    ['en' => 'Ain El Zeit', 'ar' => 'عين الزيت'],
                    ['en' => 'Wadi Khaled Border', 'ar' => 'حدود وادي خالد'],
                    ['en' => 'Khirbet Daoud', 'ar' => 'خربة داوود'],
                    ['en' => 'Wadi Faara', 'ar' => 'وادي فعرا'],
                    ['en' => 'Boudai El Hermel', 'ar' => 'بوداي الهرمل'],
                    ['en' => 'Douris Hermel', 'ar' => 'دورس الهرمل'],
                    ['en' => 'Kneiseh', 'ar' => 'كنيسة'],
                    ['en' => 'Ain Tinta Hermel', 'ar' => 'عين تنتا الهرمل'],
                    ['en' => 'Jroud Hermel', 'ar' => 'جرود الهرمل'],
                    ['en' => 'Wadi Ouyoun', 'ar' => 'وادي عيون'],
                    ['en' => 'Wadi Ennosour', 'ar' => 'وادي النسور'],
                ],
            ],
            [
                'en' => 'Qaa',
                'ar' => 'القاع',
                'areas' => [
                    ['en' => 'Qaa El Reem', 'ar' => 'القاع الريم'],
                    ['en' => 'Qaa Plains', 'ar' => 'سهل القاع'],
                    ['en' => 'Qaa Town Center', 'ar' => 'وسط القاع'],
                    ['en' => 'Ain El Labweh Road', 'ar' => 'طريق عين اللبوة'],
                    ['en' => 'Mrah Es Srayj', 'ar' => 'مرج السريج'],
                    ['en' => 'Al Arida', 'ar' => 'العارضة'],
                    ['en' => 'Jroud Qaa', 'ar' => 'جرود القاع'],
                    ['en' => 'Tallet Qaa', 'ar' => 'تلة القاع'],
                    ['en' => 'Hay El Marj', 'ar' => 'حي المرج'],
                    ['en' => 'Masnaa Border Road', 'ar' => 'طريق المصنع'],
                ],
            ],
            [
                'en' => 'Beqaa Gharbi',
                'ar' => 'البقاع الغربي',
                'areas' => [
                    ['en' => 'Jeb Jennine', 'ar' => 'جب جنين'],
                    ['en' => 'Lala', 'ar' => 'لالا'],
                    ['en' => 'Machghara', 'ar' => 'مشغرة'],
                    ['en' => 'Kamed El Loz', 'ar' => 'كامد اللوز'],
                    ['en' => 'Saghbine', 'ar' => 'صغبين'],
                    ['en' => 'Aitanit', 'ar' => 'عيطنت'],
                    ['en' => 'Mansoura', 'ar' => 'المنصورة'],
                    ['en' => 'Ain Zebdeh', 'ar' => 'عين زبدة'],
                    ['en' => 'Bireh', 'ar' => 'البيرة'],
                    ['en' => 'Maydoun', 'ar' => 'ميدون'],
                    ['en' => 'Khalwat', 'ar' => 'الخلوات'],
                    ['en' => 'Ghazzeh', 'ar' => 'غزة'],
                    ['en' => 'Ain Et Tineh', 'ar' => 'عين التينة'],
                    ['en' => 'Marj', 'ar' => 'المرج'],
                ],
            ],
            [
                'en' => 'Dahieh',
                'ar' => 'الضاحية الجنوبية',
                'areas' => [
                    ['en' => 'Haret Hreik', 'ar' => 'حارة حريك'],
                    ['en' => 'Bir Abed', 'ar' => 'بير العبد'],
                    ['en' => 'Ghobeiry', 'ar' => 'غبيري'],
                    ['en' => 'Chiyah', 'ar' => 'الشياح'],
                    ['en' => 'Tahwitet El Ghadir', 'ar' => 'تحويطة الغدير'],
                    ['en' => 'Laylaki', 'ar' => 'ليلكي'],
                    ['en' => 'Hay El Sellom', 'ar' => 'حي السلم'],
                    ['en' => 'Sfeir', 'ar' => 'صفير'],
                    ['en' => 'Msharrafieh', 'ar' => 'المشرفية'],
                    ['en' => 'Airport Highway', 'ar' => 'أوتوستراد المطار'],
                    ['en' => 'Kansara', 'ar' => 'الكنسارة'],
                    ['en' => 'Hay El Raml', 'ar' => 'حي الرمل'],
                    ['en' => 'Jnah (Dahieh side)', 'ar' => 'الجناح (جانب الضاحية)'],
                    ['en' => 'Borj El Brajneh', 'ar' => 'برج البراجنة'],
                    ['en' => 'Ouzai', 'ar' => 'الأوزاعي'],
                    ['en' => 'Sabra (bordering)', 'ar' => 'صبرا'],
                    ['en' => 'Rasoul Al Aazam Area', 'ar' => 'منطقة الرسول الأعظم'],
                ],
            ],
        ];
        foreach ($cities as $cityData) {
            if (!isset($cityData['en']) || !isset($cityData['ar'])) {
                dd("Invalid city data:", $cityData);
            }

            $city = City::firstOrCreate(
                ['name_en' => $cityData['en']],
                ['name_ar' => $cityData['ar']]
            );

            if (!empty($cityData['areas'])) {
                foreach ($cityData['areas'] as $area) {
                    Area::firstOrCreate(
                        ['name_en' => $area['en'], 'city_id' => $city->id],
                        ['name_ar' => $area['ar']]
                    );
                }
            }
        }
    }
}
